version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - 5173:3000
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 3001:3001
    command: dev 
    volumes: 
      - ./backend/src:/backend/src
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      - DB_USER=root
      - DB_PASS=confeitariaka
      - DB_HOST=db
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.32
    container_name: banco
    ports:
      - 3306:3306
    environment:
      - MYSQLUSER=root
      - MYSQLPASSWORD=db
      - MYSQLDATABASE=confeitariaka
      - MYSQLHOST=db
      - MYSQLPORT=3306
      - MYSQL_ROOT_PASSWORD=confeitariaka
      - MYSQL_DATABASE=db
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE